name: Action to build and publish the project as a nuget package to github package registry

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      Version: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch-depth is needed for GitVersion

      # Install and calculate the new version with GitVersion
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: 5.x

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        id: gitversion

      - name: Display GitVersion outputs
        run: |
          echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
          echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"

      # Build/pack the project
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Build Project
        run: dotnet build Seguridad/SeguridadMW.Middleware/SeguridadMW.Middleware.csproj -c Release

      - name: Pack NuGet package
        run: dotnet pack Seguridad/SeguridadMW.Middleware/SeguridadMW.Middleware.csproj -p:Version='${{ steps.gitversion.outputs.SemVer }}' -c Release
      # SUBIR el .nupkg como artifact
      - name: Upload NuGet Package
        uses: actions/upload-artifact@v4
        with:
          name: nugetPackage
          path: Seguridad/SeguridadMW.Middleware/bin/Release/*.nupkg

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download packaged artifacts
        uses: actions/download-artifact@v3
        with:
          name: nugetPackage

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.build.outputs.Version }}
          name: Release ${{ needs.build.outputs.Version }}
          artifacts: "*.nupkg"
          token: ${{ secrets.PAQUETES_TOKEN }}
